name 'ihs61'
maintainer 'Li Lin'
maintainer_email 'lin.li@sc.com'
license 'all_rights'
description 'Installs IBM HTTP Server 6.1'
long_description 'Installs IBM HTTP Server 6.1'
version '0.1.0'
depends 'was61nd', '~> 0.1.0'
